<a href="https://colab.research.google.com/github/divyasuresh1450-ai/Python-For-Data-Science-/blob/main/practical4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Name:Divya Suresh Gaikwad
ROLLno:SY_A-64

Practical no:4


Aim:To perform numerical computations using the NumPy library in Python and understand its operations like array handling, mathematical, and statistical analysis.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving aistudent.csv to aistudent.csv


In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv("aistudent.csv")
arr = data.values

In [ ]:
import numpy as np

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [ ]:
np.array(arr)
np.zeros((3,3))
np.ones((2,2))
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

arr.shape
arr.reshape(2, -1)
arr.flatten()

array([1, 15, 'Female', ..., 'Learning', 'Improved', 'High'], dtype=object)

In [ ]:
arr[0]
arr[:, 1]
arr[1:5]


array([[2, 21, 'Female', 'University', 'Chennai', 'Copilot', 1.7,
        'Coding', 'Slight Decline', 'High'],
       [3, 22, 'Male', 'University', 'Bangalore', 'Gemini', 1.5,
        'Learning', 'Improved', 'Low'],
       [4, 22, 'Male', 'College', 'Hyderabad', 'ChatGPT', 3.8,
        'Research', 'Improved', 'Low'],
       [5, 22, 'Male', 'College', 'Hyderabad', 'Gemini', 5.2, 'Coding',
        'Slight Decline', 'Low']], dtype=object)

In [ ]:
np.sum(arr, axis=0)
np.sum(arr, axis=1)

array([ 6, 15])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [ ]:
np.sum(arr, axis=0)
np.sum(arr, axis=1)

array([ 6, 15])

In [ ]:
np.sum(arr)

np.int64(21)

In [ ]:
np.sum(arr, axis=0)   # column-wise
np.sum(arr, axis=1)   # row-wise

array([ 6, 15])

In [ ]:
arr > 50
arr[arr > 50]



array([], dtype=int64)

In [ ]:
np.sort(arr)
np.argsort(arr)


array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.dot(arr, arr.T)
np.transpose(arr)



array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.random.rand(3,3)
np.random.randint(1,100,(3,3))


array([[24, 75, 23],
       [62,  5, 43],
       [87, 19, 88]])

In [ ]:
arr + np.array([1,2,3])


array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
np.unique(arr)


array([1, 2, 3, 4, 5, 6])

1. Role of NumPy in Python Scientific Computing

NumPy is the core library for numerical computing in Python.Provides multidimensional arrays.Supports fast mathematical computations,
Acts as the base for libraries like Pandas, Matplotlib, Scikit-learn,Enables vectorized operations.

2. Why NumPy is Faster than Pure Python

Uses C-based implementation internally,Avoids Python loops uses vectorization,Efficient memory usage (continuous memory blocks),Supports broadcasting.

3. Mathematical Operations in NumPy


Arithmetic → + - * /,Statistical → mean, median, std,Linear algebra : dot product, matrix multiplication,Trigonometric : sin, cos,Logarithmic : log, exp..

4. Indexing and Slicing in NumPy
Indexing:

arr[0]       # first element
arr[-1]      # last element

Slicing:

arr[1:5]     # elements from index 1 to 4
arr[:, 1]    # all rows, column 1

5. Integration with Other Libraries

a. Pandas:Uses NumPy arrays internally

import pandas as pd
df = pd.DataFrame(arr)

b. Matplotlib:Used for plotting NumPy data

import matplotlib.pyplot as plt
plt.plot(arr)

c. Scikit-learn:Accepts NumPy arrays for ML models
from sklearn.linear_model import LinearRegression
model.fit(X, y).






